from fastapi.routing import APIRouter
from pydantic import BaseModel, Field
from openai import OpenAI
from invokeai.app.services.config import get_config

llm_router = APIRouter(prefix="/v1/llm", tags=["llm"])

class LLMRequest(BaseModel):
    text: str = Field(description="The text to send to the LLM")
    model: str | None = Field(default=None, description="The name of the model currently used in the frontend")
    model_name: str | None = Field(default=None, description="The name of the model currently used in the frontend, for prompt generation")

class TranslationRequest(BaseModel):
    text: str = Field(description="The text to translate")

class LLMResponse(BaseModel):
    text: str = Field(description="The text generated by the LLM")

# Define the base system prompt for prompt generation
BASE_SYSTEM_PROMPT = """
You are an expert prompt engineer.  
Your ONLY task is to output a single **detailed image-generation prompt**, nothing else.  
Do NOT include explanations, notes, structure, or formatting. Only the prompt itself in plain English.

The prompt must be in English.
"""

# Define the system prompt for translation
TRANSLATION_SYSTEM_PROMPT = """
You are a highly accurate and fluent translator.
Your task is to translate the user's input into the specified target language.
If the text is already in the target language, simply correct any grammatical or spelling errors.
Provide only the translated text, without any additional commentary or conversational filler.
"""

# Initialize OpenAI client globally
config = get_config()
openai_api_key = config.openai_api_key

if not openai_api_key:
    raise ValueError("OpenAI API key not found in InvokeAI configuration. Please set it in invokeai.yaml or via INVOKEAI_OPENAI_API_KEY environment variable.")

client = OpenAI(api_key=openai_api_key)

@llm_router.post(
    "/generate",
    operation_id="generate_text",
    responses={
        200: {"model": LLMResponse},
    },
)
async def generate_text(
    req: LLMRequest,
) -> LLMResponse:
    """Generates text using an LLM"""
    user_input = f"### USER_DESCRIPTION: {req.text}"
    model = req.model
    model_name = req.model_name
    
    # Dynamically adjust the system prompt based on the model name
    system_prompt = BASE_SYSTEM_PROMPT
    if model:
        system_prompt = f"{BASE_SYSTEM_PROMPT}\n\nThe current image generation model is: {model}. Tailor your prompt generation specifically for this model. "

    if model_name and 'pony' in model_name.lower():
        system_prompt += f"\n\nThe model name is: {model_name}. Use keyword instead of sentence. Put the keywords into <KEYWORDS> separated by comma : "
        system_prompt += f"\n\n cinematic photo, score_9, score_8_up, score_7_up, <KEYWORD>, depth of field, highly detailed, high contrast, film grain, Rim Lighting, Rays of Shimmering Light , 35mm photograph, film, bokeh, professional, 4k, highly detailed"

    from openai.types.chat import ChatCompletionSystemMessageParam, ChatCompletionUserMessageParam

    messages = [
        ChatCompletionSystemMessageParam(role="system", content=system_prompt),
        ChatCompletionUserMessageParam(role="user", content=user_input),
    ]

    try:
        response = client.chat.completions.create(
            model="gpt-4o-mini", 
            messages=messages,
            max_tokens=2000,  # Adjust as needed
        )
        generated_text = response.choices[0].message.content or ""
    except Exception as e:
        # Handle API errors, e.g., invalid key, rate limits, etc.
        print(f"Error calling OpenAI API: {e}")
        generated_text = f"Error generating text: {e}"

    return LLMResponse(text=generated_text)

@llm_router.post(
    "/translate",
    operation_id="translate_text",
    responses={
        200: {"model": LLMResponse},
    },
)
async def translate_text(
    req: TranslationRequest,
) -> LLMResponse:
    """Translates text using an LLM"""
    text_to_translate = req.text
    target_language = "english"

    system_prompt = f"{TRANSLATION_SYSTEM_PROMPT}\nTranslate the following text into {target_language}."

    from openai.types.chat import ChatCompletionSystemMessageParam, ChatCompletionUserMessageParam

    messages = [
        ChatCompletionSystemMessageParam(role="system", content=system_prompt),
        ChatCompletionUserMessageParam(role="user", content=text_to_translate),
    ]

    try:
        response = client.chat.completions.create(
            model="gpt-4o-mini",  # You can change this to "gpt-4" or another suitable model
            messages=messages,
            max_tokens=2000,  # Adjust as needed
        )
        translated_text = response.choices[0].message.content or ""
    except Exception as e:
        print(f"Error calling OpenAI API for translation: {e}")
        translated_text = f"Error translating text: {e}"

    return LLMResponse(text=translated_text)
